### ISSUE TITLE
Skip certain dependency scopes

### ISSUE THREAD

**Issue by reiniertimmer** [advanced-security/maven-dependency-submission-action#20]
The action currently generates a full dependency tree, including all `test` dependencies.

If you are only interested in `compile` scope dependencies, there is currently no way to skip over this. It would be very convenient if this can be configured in this action somehow

**Comment by peter-murray** [comment]
Whilst I understand the ask, if the dependency graph is already turned on for the repository, then the POM files will be being analysed and those test dependencies will already be recorded (possibly without a version number depending upon how you specify them and control the versions).

Excluding them from this level of detection would not remove them from the other, so I would tend to err on the side of being complete over having inconsistent holes in the test dependencies.

Can you possibly expand on the use case here?

**Comment by jebeaudet** [comment]
I'm also interested in this.

While you're right that currently, if you have the dependency graph turned on for a repo, it'll pick up those test dependencies, I still think this should be an option for this action. The reason is that, in most cases, you're only interested in non test dependencies for vulnerability checking, at least from a compliance perspective since test dependencies are not included in the final package.

Now, this should also be an option in the dependency graph (I'm trying to find out where I can request/follow an issue for this) and when it is, then this action will also need to exclude test dependencies to have a proper dependency graph so that's why I think it should be an option for this action.

My ideal though would be that the dependency graph built-in does what this action does and picks up transitive dependency  of course.

**Comment by reiniertimmer** [comment]
Hi @peter-murray 

sorry I missed your comment, but the remark about the default dependency graph already containing all scopes is interesting. I am leaning to prefer consistency over flexibility.

Our use case is that we want to scan for vulnerabilities in production dependencies, and adding test dependencies would just create additional noise: it also makes it harder to see if a vulnerable dependency is actually used in a compiled release, or if it has only been used for the testing phase.

They are both bad though: even if vulnerabilities are not used in production code, they should preferably also not be used in the build/testing phases. But the urgency is probably a bit different.

Unfortunately, I have to agree that the GitHub dependency graph doesn't show this kind of scoping information either, so hiding test scoped dependencies from one view (submitted) and displaying then in the other (automatically scanned) also feels a bit awkward.

**Comment by Gby56** [comment]
Hi ! Thanks for bringing this up @reiniertimmer, I did not know either that the regular "background" scanning was picking up test/dev dependencies too.
I do agree that we should have a filtering ability to narrow results to only production scopes. This should be reflected up to the whole organization "Security" tab. 

What I suspect is that Github would have to support a distinct property for every dependency you upload, to mark it as production or non-production.
I don't know the API exactly, I see that it supports SBOM uploads and SPDX, and from the dependency submission toolkit it's also not clear.

**Comment by reiniertimmer** [comment]
@ryewilson interesting, worth a try!

**Comment by jebeaudet** [comment]
the `ignoreAllNonTestScoped` is not excluding the test scoped dependencies, from the documentation : 
> Ignore all dependencies that are used only in test but not test-scoped

**Comment by jebeaudet** [comment]
Well I've tested it and it seems to work : 
```
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
        with:
          directory: .
          maven-args: -Dscopes=compile,provided,runtime,system
```
The output of the job does not pick up the test scoped dependencies. Thanks for the cue @ryewilson, I'll integrate this on my end.
